<?php
/**
 * @file
 * Configuracion y modificacion de funciones y preprocesos en formularios, entidades del sitio. Findeter
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter
 */

function findeter_webfinde_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $rolesUser = \Drupal::currentUser()->getRoles();
  //dpm($form);
  /* ============================================
  CONVOCATORIAS
  =============================================== */
  if($form['#id'] == 'node-convocatorias-form' || $form['#id'] == 'node-convocatorias-edit-form'){

    /* ============================================
    CONVOCATORIAS
    =============================================== */
    $form['#attached']['library'][] = 'findeter_webfinde/global-scripts';

    

    $rol = "";

    if(in_array('abogado',$rolesUser)){

      $rol = 'abogado';

      $form['#attributes'] = array(
        'rol' => $rol,
      );

    }

  }

}

function findeter_webfinde_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) { 
  $rolesUser = \Drupal::currentUser()->getRoles();

  /* ============================================
  ARCHIVOS CONVOCATORIAS MEDIA
  =============================================== */
  if(in_array('abogado',$rolesUser)){
    hide($entity_form['created']);
  }
}

