<?php
/**
 * @file
 * Configuracion y modificacion de funciones y preprocesos en formularios, entidades del sitio. Findeter
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\devel\Plugin\Devel\Dumper\Kint;
use Drupal\user\Entity\User;

/**
 * Implements findeter_webfinde_cron().
 * @author 3ddesarrollo <email@email.com>
 */
function findeter_webfinde_cron() {

  /* ============================================
  CONVOCATORIAS
  script que se ejecuta para borrar archivos sueltos
  en la carpeta private y que no se han utilizado o cargado
  por parte de algun usuario.
  =============================================== */
  /*$fileSystem = \Drupal::service('file_system');
  $files = $fileSystem->scanDirectory('private://', '/\.pdf$|\.txt$/', ['recurse' => FALSE]);

  if(sizeof($files)){
    foreach ($files as $file) {
      $fileSystem->unlink($file->uri);
    }
  }*/
}

/**
 * Implements hook_form_alter
 */

function findeter_webfinde_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $rolesUser = \Drupal::currentUser()->getRoles();
  /* ============================================
  CONVOCATORIAS
  =============================================== */
  if($form['#id'] == 'node-convocatorias-form' || $form['#id'] == 'node-convocatorias-edit-form'){

    $form['#attached']['library'][] = 'findeter_webfinde/global-scripts';

    $dataRemoveSumbit = "";

    if(in_array('abogado',$rolesUser) || in_array('c_vicetecnica', $rolesUser)){

      $dataRemoveSumbit = 'data-remove-sumbit';

      $form['#attributes'] = array(
        'data-remove-sumbit' => $dataRemoveSumbit,
      );

    }

  }

  if ($form['#id'] == 'node-convocatorias-edit-form') {
    $form['title']['widget'][0]['value']['#attributes']['readonly'] = 'readonly';
  }

}

function findeter_webfinde_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  $rolesUser = \Drupal::currentUser()->getRoles();
  /* ============================================
  ARCHIVOS CONVOCATORIAS MEDIA
  =============================================== */
  if(in_array('abogado',$rolesUser)){
    hide($entity_form['created']);
  }
}

