<?php

/**
 * @file
 * Primary module hooks for findeter_rediscount module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
  * Implements hook_theme().
  */
function findeter_rediscount_theme($existing, $type, $theme, $path) {
  return [
    'findeter_rediscount_sectors' => [
      'template' => 'findeter-rediscount-sectors',
      'variables' => [
        'data' => NULL,
        'count' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function findeter_rediscount_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === 'node_entities_rediscount_edit_form') {
    //dump($form);
  }
}

function findeter_rediscount_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  //dump($element['#paragraph_type']);
}

function findeter_rediscount_paragraphs_widget_actions_alter(array &$widget_actions, array &$context) {
  //dump($widget_actions);
}

function findeter_rediscount_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  // Set a new label for the my_layout plugin instead of the one
  // provided in the annotation.
 dump($paragraphs_behavior);
}