<?php

/**
 * @file
 * Primary module hooks for findeter_rediscount module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
use Drupal\Core\Form\FormStateInterface;

/**
  * Implements hook_theme().
  */
function findeter_rediscount_theme($existing, $type, $theme, $path) {
  return [
    'findeter_rediscount_sectors' => [
      'template' => 'findeter-rediscount-sectors',
      'variables' => [
        'data' => NULL,
        'count' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function findeter_rediscount_form_alter(&$form, $form_state, $form_id) {
  // $forms = $form['field_info_rediscount_entities']['widget']['add_more']['#suffix'] = '';
  //dump($form);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function findeter_rediscount_form_node_form_alter(&$form, $form_state, $form_id) {

  $node = $form_state->getFormObject()->getEntity();

  switch($node->getType()){

    /* ============================================
    ENTIDAD DE REDESCUENTO
    =============================================== */
    case 'entities_rediscount':
      // Informacion y uso de redescuento
      $form['field_info_rediscount_entities']['widget']['add_more']['#suffix'] = '';
      $form['field_info_rediscount_entities']['widget']['add_more']['add_more_button_info_programs_line_credit']['#value'] = 'Añadir información y uso redescuento';

      // Infomracion de interes
      $form['field_info_interest_entities']['widget']['add_more']['#suffix'] = '';
      $form['field_info_interest_entities']['widget']['add_more']['add_more_button_info_programs_line_credit']['#value'] = 'Añadir información de interes';
    break;

     /* ============================================
    PROGRAMAS DE REDESCUENTO
    =============================================== */
    case 'programs':
      // Informacion de producto
      $form['field_info_product_prgms']['widget']['add_more']['#suffix'] = '';
      $form['field_info_product_prgms']['widget']['add_more']['add_more_button_info_programs_line_credit']['#value'] = 'Añadir Información de producto';
    break;

    /* ============================================
    LINEAS DE CREDITO
    =============================================== */
    case 'lines_credit':
      // Informacion de producto
      $form['field_info_product_linecredit']['widget']['add_more']['#suffix'] = '';
      $form['field_info_product_linecredit']['widget']['add_more']['add_more_button_info_programs_line_credit']['#value'] = 'Añadir Información de producto';
    break;


  }
}

/**
 * Implements hook__field_widget_paragraphs_form_alter()
 */
function findeter_rediscount_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {

  /* ============================================
  Pragraphs Informacion [programs/linea credito/redescunto]
  =============================================== */
  if ( $element['#paragraph_type'] == 'info_programs_line_credit') {
    $element['top']['type']['label']['#markup'] = '';
  }

}

/**
 * Implements hook_preprocess_views_view_table()
 */
function findeter_rediscount_preprocess_views_view_table(&$variables){

  $view = $variables['view'];
  $rows = $variables['rows'];
  $headers = $variables['header'];

  if($view->storage->id() == 'rediscount' && $view->current_display == 'table_line_credit'){

    $data = [];
    $i = 0;

    foreach ($headers as $keyh => $header) {
      $datas1 = [
        'title_column' => $keyh,
        'title' => $header['content'],
      ];

      $datas2 = [];
      foreach ($rows as $keyr => $row) {
        $datas2[$keyr] = [
          "$keyh" => $row['columns'][$keyh]['content'][0]['field_output']['#markup'],
        ];
      }

      $data[$i] = array_merge($datas1, ["rows" => $datas2]);
      $i++;

    }

    $variables['data'] = $data;

  }
}

 /**
 * Implements hook_form_views_exposed_form_alter()
 *
 */
function findeter_rediscount_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {

  if($form['#id'] == 'views-exposed-form-rediscount-filter-line-credit'){

    /* ===== ===== TITULO DEL FORMULARIO ===== ===== */
    if (isset($form['field_means_progms_value_collapsible'])) {
      $form['field_means_progms_value_collapsible']['#prefix'] = '<h5 class="text-left mb-3">'.t('Filtrar líneas por').'</h5>';
    }

  }
}

/**
 * Implements hook_views_query_alter().
 */
function findeter_rediscount_views_query_alter($view, $query) {

  if ($view->id() == 'rediscount' && $view->getDisplay()->display['id'] == 'filter_line_credit') {
    $query->distinct = true;
  }
}
