_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: es
uuid: fd820dc8-1528-420d-a4ca-69838cc92986
name: Findeter
mail: findeter@findeter.gov.co
slogan: ''
page:
  403: ''
  404: /node/85
  front: /inicio
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
