<?php 

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function findeter_user_form_request_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.findeter_user_form_request':
      $output = '';
      $output .= '<h3>Acerca de</h3>';
      $output .= '<p>Este módulo permite registrar los reclamos, peticiones, solicitudes, etc., para la institución Findeter, con campos y comportamientos específicos.</p>';
      $output .= '<p>Para mayor comprensión se contruyó el formulario mediante pasos multiples con comportamiento ajax.</p>';
      $output .= '<h3>Uso</h3>';
      $output .= '<dl>';
      $output .= '<dt>Configuración</dt>';
      $output .= '<dd>Para configurar los principales parámetros necesarios para el funcionamiento del módulo, puede consultar la <a href="/admin/config/findeter_user_form_request/admin">página administrativa</a> del módulo</dd>';
      $output .= '<dd>Una vez instalado el módulo, puede consultar el formulario en la <a href="/user-request-form">dirección</a></dd>';
      $output .= '<dt>Configuración</dt>';
      $output .= '<dd>Para configurar los principales parámetros necesarios para el funcionamiento del módulo, puede consultar la <a href="/admin/config/findeter_user_form_request/admin">página administrativa</a> del módulo</dd>';
      $output .= '<dd>Una vez instalado el módulo, puede consultar el formulario en la <a href="/user-request-form">dirección</a> para realizar el registro de PQRS mediante la web.</dd>';
      $output .= '<dd>Para usuarios registrados, que tengan los derechos suficientes para administrar los request, pueden visitar <a href="/admin/user-request-admin">esta página administrativa</a> donde podrá realizar las acciones que le son permitidas.</dd>';
      $output .= '<dd>Para usuarios administradores, pueden visitar <a href="/admin/request-admin">esta página administrativa</a> donde podrá realizar las acciones que le son permitidas.</dd>';
      $output .= '</dl>';
      return $output;
  }
}


/**
 * Implements hook_preprocess_views_view_field()
 */
function findeter_user_form_request_preprocess_views_view_field(&$variables) {

  $view = $variables['view'];
  $field = $variables['field'];

  if ($view->storage->id() == 'user_request_views'){

      if($field->field == 'field_answer'){
        // change the output for answer state pages 1 and 2
        if($view->current_display == 'page_1' || $view->current_display == 'page_2'){
          if($variables['output'] == ''){
            $variables['output'] = 'Abierta';
          }else{
            $variables['output'] = 'Cerrada por: '.strip_tags($view->field['uid']->original_value);
          }
        }
      }

      // if PQR has an answer, don't show "asign" and "answer" links
      if($field->field == 'nid' && ($field->label() == 'Asignar' || $field->label() == 'Responder' )){
        if($view->field['field_answer']->original_value != ''){
          $variables['output'] = '';
        }
      }

  }

}